"""inventorymovement_fixed

Revision ID: fffaf6b69dd9
Revises: d615bc1aa10e
Create Date: 2026-10-05 20:58:13.826942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffaf6b69dd9'
down_revision: Union[str, Sequence[str], None] = 'd615bc1aa10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movement', 'reference_type')
    op.drop_column('inventory_movement', 'reference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_movement', sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('inventory_movement', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
